services:
  manager:
    build:
      context: .
      dockerfile: ./deploy/manager/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WORKER_URLS=http://worker-1:8080,http://worker-2:8080
      - QT_LOGGING_RULES="*=true"
    networks:
      - crackhash-net

  worker-1:
    build:
      context: .
      dockerfile: ./deploy/worker/Dockerfile
    environment:
      - PORT=8080
      - MANAGER_URL=http://manager:8080
      - QT_LOGGING_RULES="*=true"]
    networks:
      - crackhash-net
  
  worker-2:
    build:
      context: .
      dockerfile: ./deploy/worker/Dockerfile
    environment:
      - PORT=8080
      - MANAGER_URL=http://manager:8080
      - QT_LOGGING_RULES="*=true"
    networks:
      - crackhash-net

networks:
  crackhash-net:
    driver: bridge

