// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "request.hxx"

namespace dto
{
  // CrackHashManagerRequest
  //

  const CrackHashManagerRequest::RequestId_type& CrackHashManagerRequest::
  RequestId () const
  {
    return this->RequestId_.get ();
  }

  CrackHashManagerRequest::RequestId_type& CrackHashManagerRequest::
  RequestId ()
  {
    return this->RequestId_.get ();
  }

  void CrackHashManagerRequest::
  RequestId (const RequestId_type& x)
  {
    this->RequestId_.set (x);
  }

  void CrackHashManagerRequest::
  RequestId (::std::unique_ptr< RequestId_type > x)
  {
    this->RequestId_.set (std::move (x));
  }

  const CrackHashManagerRequest::PartNumber_type& CrackHashManagerRequest::
  PartNumber () const
  {
    return this->PartNumber_.get ();
  }

  CrackHashManagerRequest::PartNumber_type& CrackHashManagerRequest::
  PartNumber ()
  {
    return this->PartNumber_.get ();
  }

  void CrackHashManagerRequest::
  PartNumber (const PartNumber_type& x)
  {
    this->PartNumber_.set (x);
  }

  const CrackHashManagerRequest::PartCount_type& CrackHashManagerRequest::
  PartCount () const
  {
    return this->PartCount_.get ();
  }

  CrackHashManagerRequest::PartCount_type& CrackHashManagerRequest::
  PartCount ()
  {
    return this->PartCount_.get ();
  }

  void CrackHashManagerRequest::
  PartCount (const PartCount_type& x)
  {
    this->PartCount_.set (x);
  }

  const CrackHashManagerRequest::Hash_type& CrackHashManagerRequest::
  Hash () const
  {
    return this->Hash_.get ();
  }

  CrackHashManagerRequest::Hash_type& CrackHashManagerRequest::
  Hash ()
  {
    return this->Hash_.get ();
  }

  void CrackHashManagerRequest::
  Hash (const Hash_type& x)
  {
    this->Hash_.set (x);
  }

  void CrackHashManagerRequest::
  Hash (::std::unique_ptr< Hash_type > x)
  {
    this->Hash_.set (std::move (x));
  }

  const CrackHashManagerRequest::MaxLength_type& CrackHashManagerRequest::
  MaxLength () const
  {
    return this->MaxLength_.get ();
  }

  CrackHashManagerRequest::MaxLength_type& CrackHashManagerRequest::
  MaxLength ()
  {
    return this->MaxLength_.get ();
  }

  void CrackHashManagerRequest::
  MaxLength (const MaxLength_type& x)
  {
    this->MaxLength_.set (x);
  }

  const CrackHashManagerRequest::Alphabet_type& CrackHashManagerRequest::
  Alphabet () const
  {
    return this->Alphabet_.get ();
  }

  CrackHashManagerRequest::Alphabet_type& CrackHashManagerRequest::
  Alphabet ()
  {
    return this->Alphabet_.get ();
  }

  void CrackHashManagerRequest::
  Alphabet (const Alphabet_type& x)
  {
    this->Alphabet_.set (x);
  }

  void CrackHashManagerRequest::
  Alphabet (::std::unique_ptr< Alphabet_type > x)
  {
    this->Alphabet_.set (std::move (x));
  }


  // Alphabet
  //

  const Alphabet::symbols_sequence& Alphabet::
  symbols () const
  {
    return this->symbols_;
  }

  Alphabet::symbols_sequence& Alphabet::
  symbols ()
  {
    return this->symbols_;
  }

  void Alphabet::
  symbols (const symbols_sequence& s)
  {
    this->symbols_ = s;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace dto
{
  // CrackHashManagerRequest
  //

  CrackHashManagerRequest::
  CrackHashManagerRequest (const RequestId_type& RequestId,
                           const PartNumber_type& PartNumber,
                           const PartCount_type& PartCount,
                           const Hash_type& Hash,
                           const MaxLength_type& MaxLength,
                           const Alphabet_type& Alphabet)
  : ::xml_schema::type (),
    RequestId_ (RequestId, this),
    PartNumber_ (PartNumber, this),
    PartCount_ (PartCount, this),
    Hash_ (Hash, this),
    MaxLength_ (MaxLength, this),
    Alphabet_ (Alphabet, this)
  {
  }

  CrackHashManagerRequest::
  CrackHashManagerRequest (const RequestId_type& RequestId,
                           const PartNumber_type& PartNumber,
                           const PartCount_type& PartCount,
                           const Hash_type& Hash,
                           const MaxLength_type& MaxLength,
                           ::std::unique_ptr< Alphabet_type > Alphabet)
  : ::xml_schema::type (),
    RequestId_ (RequestId, this),
    PartNumber_ (PartNumber, this),
    PartCount_ (PartCount, this),
    Hash_ (Hash, this),
    MaxLength_ (MaxLength, this),
    Alphabet_ (std::move (Alphabet), this)
  {
  }

  CrackHashManagerRequest::
  CrackHashManagerRequest (const CrackHashManagerRequest& x,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    RequestId_ (x.RequestId_, f, this),
    PartNumber_ (x.PartNumber_, f, this),
    PartCount_ (x.PartCount_, f, this),
    Hash_ (x.Hash_, f, this),
    MaxLength_ (x.MaxLength_, f, this),
    Alphabet_ (x.Alphabet_, f, this)
  {
  }

  CrackHashManagerRequest::
  CrackHashManagerRequest (const ::xercesc::DOMElement& e,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    RequestId_ (this),
    PartNumber_ (this),
    PartCount_ (this),
    Hash_ (this),
    MaxLength_ (this),
    Alphabet_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void CrackHashManagerRequest::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // RequestId
      //
      if (n.name () == "RequestId" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< RequestId_type > r (
          RequestId_traits::create (i, f, this));

        if (!RequestId_.present ())
        {
          this->RequestId_.set (::std::move (r));
          continue;
        }
      }

      // PartNumber
      //
      if (n.name () == "PartNumber" && n.namespace_ ().empty ())
      {
        if (!PartNumber_.present ())
        {
          this->PartNumber_.set (PartNumber_traits::create (i, f, this));
          continue;
        }
      }

      // PartCount
      //
      if (n.name () == "PartCount" && n.namespace_ ().empty ())
      {
        if (!PartCount_.present ())
        {
          this->PartCount_.set (PartCount_traits::create (i, f, this));
          continue;
        }
      }

      // Hash
      //
      if (n.name () == "Hash" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< Hash_type > r (
          Hash_traits::create (i, f, this));

        if (!Hash_.present ())
        {
          this->Hash_.set (::std::move (r));
          continue;
        }
      }

      // MaxLength
      //
      if (n.name () == "MaxLength" && n.namespace_ ().empty ())
      {
        if (!MaxLength_.present ())
        {
          this->MaxLength_.set (MaxLength_traits::create (i, f, this));
          continue;
        }
      }

      // Alphabet
      //
      if (n.name () == "Alphabet" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< Alphabet_type > r (
          Alphabet_traits::create (i, f, this));

        if (!Alphabet_.present ())
        {
          this->Alphabet_.set (::std::move (r));
          continue;
        }
      }

      break;
    }

    if (!RequestId_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "RequestId",
        "");
    }

    if (!PartNumber_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "PartNumber",
        "");
    }

    if (!PartCount_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "PartCount",
        "");
    }

    if (!Hash_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "Hash",
        "");
    }

    if (!MaxLength_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "MaxLength",
        "");
    }

    if (!Alphabet_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "Alphabet",
        "");
    }
  }

  CrackHashManagerRequest* CrackHashManagerRequest::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class CrackHashManagerRequest (*this, f, c);
  }

  CrackHashManagerRequest& CrackHashManagerRequest::
  operator= (const CrackHashManagerRequest& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->RequestId_ = x.RequestId_;
      this->PartNumber_ = x.PartNumber_;
      this->PartCount_ = x.PartCount_;
      this->Hash_ = x.Hash_;
      this->MaxLength_ = x.MaxLength_;
      this->Alphabet_ = x.Alphabet_;
    }

    return *this;
  }

  CrackHashManagerRequest::
  ~CrackHashManagerRequest ()
  {
  }

  // Alphabet
  //

  Alphabet::
  Alphabet ()
  : ::xml_schema::type (),
    symbols_ (this)
  {
  }

  Alphabet::
  Alphabet (const Alphabet& x,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    symbols_ (x.symbols_, f, this)
  {
  }

  Alphabet::
  Alphabet (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f,
            ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    symbols_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void Alphabet::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // symbols
      //
      if (n.name () == "symbols" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< symbols_type > r (
          symbols_traits::create (i, f, this));

        this->symbols_.push_back (::std::move (r));
        continue;
      }

      break;
    }
  }

  Alphabet* Alphabet::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class Alphabet (*this, f, c);
  }

  Alphabet& Alphabet::
  operator= (const Alphabet& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->symbols_ = x.symbols_;
    }

    return *this;
  }

  Alphabet::
  ~Alphabet ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace dto
{
  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (const ::std::string& u,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
      ::dto::CrackHashManagerRequest_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (const ::std::string& u,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
      ::dto::CrackHashManagerRequest_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (const ::std::string& u,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
      ::dto::CrackHashManagerRequest_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::std::istream& is,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dto::CrackHashManagerRequest_ (isrc, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::std::istream& is,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dto::CrackHashManagerRequest_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::std::istream& is,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dto::CrackHashManagerRequest_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::std::istream& is,
                            const ::std::string& sid,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dto::CrackHashManagerRequest_ (isrc, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::std::istream& is,
                            const ::std::string& sid,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dto::CrackHashManagerRequest_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::std::istream& is,
                            const ::std::string& sid,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dto::CrackHashManagerRequest_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::xercesc::InputSource& i,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
      ::dto::CrackHashManagerRequest_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::xercesc::InputSource& i,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
      ::dto::CrackHashManagerRequest_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::xercesc::InputSource& i,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
      ::dto::CrackHashManagerRequest_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (const ::xercesc::DOMDocument& doc,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::unique_ptr< ::dto::CrackHashManagerRequest > (
        ::dto::CrackHashManagerRequest_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "CrackHashManagerRequest" &&
        n.namespace_ () == "dto")
    {
      ::std::unique_ptr< ::dto::CrackHashManagerRequest > r (
        ::xsd::cxx::tree::traits< ::dto::CrackHashManagerRequest, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "CrackHashManagerRequest",
      "dto");
  }

  ::std::unique_ptr< ::dto::CrackHashManagerRequest >
  CrackHashManagerRequest_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties&)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "CrackHashManagerRequest" &&
        n.namespace_ () == "dto")
    {
      ::std::unique_ptr< ::dto::CrackHashManagerRequest > r (
        ::xsd::cxx::tree::traits< ::dto::CrackHashManagerRequest, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "CrackHashManagerRequest",
      "dto");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

