// Copyright (c) 2005-2023 Code Synthesis.
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis gives permission
// to link this program with the Xerces-C++ library (or with modified
// versions of Xerces-C++ that use the same license as Xerces-C++), and
// distribute linked combinations including the two. You must obey the GNU
// General Public License version 2 in all respects for all of the code
// used other than Xerces-C++. If you modify this copy of the program, you
// may extend this exception to your version of the program, but you are
// not obligated to do so. If you do not wish to do so, delete this
// exception statement from your version.
//
// Furthermore, Code Synthesis makes a special exception for the Free/Libre
// and Open Source Software (FLOSS) which is described in the accompanying
// FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "response.hxx"

namespace dto
{
  // CrackHashWorkerResponse
  //

  const CrackHashWorkerResponse::RequestId_type& CrackHashWorkerResponse::
  RequestId () const
  {
    return this->RequestId_.get ();
  }

  CrackHashWorkerResponse::RequestId_type& CrackHashWorkerResponse::
  RequestId ()
  {
    return this->RequestId_.get ();
  }

  void CrackHashWorkerResponse::
  RequestId (const RequestId_type& x)
  {
    this->RequestId_.set (x);
  }

  void CrackHashWorkerResponse::
  RequestId (::std::unique_ptr< RequestId_type > x)
  {
    this->RequestId_.set (std::move (x));
  }

  const CrackHashWorkerResponse::PartNumber_type& CrackHashWorkerResponse::
  PartNumber () const
  {
    return this->PartNumber_.get ();
  }

  CrackHashWorkerResponse::PartNumber_type& CrackHashWorkerResponse::
  PartNumber ()
  {
    return this->PartNumber_.get ();
  }

  void CrackHashWorkerResponse::
  PartNumber (const PartNumber_type& x)
  {
    this->PartNumber_.set (x);
  }

  const CrackHashWorkerResponse::Answers_type& CrackHashWorkerResponse::
  Answers () const
  {
    return this->Answers_.get ();
  }

  CrackHashWorkerResponse::Answers_type& CrackHashWorkerResponse::
  Answers ()
  {
    return this->Answers_.get ();
  }

  void CrackHashWorkerResponse::
  Answers (const Answers_type& x)
  {
    this->Answers_.set (x);
  }

  void CrackHashWorkerResponse::
  Answers (::std::unique_ptr< Answers_type > x)
  {
    this->Answers_.set (std::move (x));
  }


  // Answers
  //

  const Answers::words_sequence& Answers::
  words () const
  {
    return this->words_;
  }

  Answers::words_sequence& Answers::
  words ()
  {
    return this->words_;
  }

  void Answers::
  words (const words_sequence& s)
  {
    this->words_ = s;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace dto
{
  // CrackHashWorkerResponse
  //

  CrackHashWorkerResponse::
  CrackHashWorkerResponse (const RequestId_type& RequestId,
                           const PartNumber_type& PartNumber,
                           const Answers_type& Answers)
  : ::xml_schema::type (),
    RequestId_ (RequestId, this),
    PartNumber_ (PartNumber, this),
    Answers_ (Answers, this)
  {
  }

  CrackHashWorkerResponse::
  CrackHashWorkerResponse (const RequestId_type& RequestId,
                           const PartNumber_type& PartNumber,
                           ::std::unique_ptr< Answers_type > Answers)
  : ::xml_schema::type (),
    RequestId_ (RequestId, this),
    PartNumber_ (PartNumber, this),
    Answers_ (std::move (Answers), this)
  {
  }

  CrackHashWorkerResponse::
  CrackHashWorkerResponse (const CrackHashWorkerResponse& x,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    RequestId_ (x.RequestId_, f, this),
    PartNumber_ (x.PartNumber_, f, this),
    Answers_ (x.Answers_, f, this)
  {
  }

  CrackHashWorkerResponse::
  CrackHashWorkerResponse (const ::xercesc::DOMElement& e,
                           ::xml_schema::flags f,
                           ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    RequestId_ (this),
    PartNumber_ (this),
    Answers_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void CrackHashWorkerResponse::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // RequestId
      //
      if (n.name () == "RequestId" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< RequestId_type > r (
          RequestId_traits::create (i, f, this));

        if (!RequestId_.present ())
        {
          this->RequestId_.set (::std::move (r));
          continue;
        }
      }

      // PartNumber
      //
      if (n.name () == "PartNumber" && n.namespace_ ().empty ())
      {
        if (!PartNumber_.present ())
        {
          this->PartNumber_.set (PartNumber_traits::create (i, f, this));
          continue;
        }
      }

      // Answers
      //
      if (n.name () == "Answers" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< Answers_type > r (
          Answers_traits::create (i, f, this));

        if (!Answers_.present ())
        {
          this->Answers_.set (::std::move (r));
          continue;
        }
      }

      break;
    }

    if (!RequestId_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "RequestId",
        "");
    }

    if (!PartNumber_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "PartNumber",
        "");
    }

    if (!Answers_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "Answers",
        "");
    }
  }

  CrackHashWorkerResponse* CrackHashWorkerResponse::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class CrackHashWorkerResponse (*this, f, c);
  }

  CrackHashWorkerResponse& CrackHashWorkerResponse::
  operator= (const CrackHashWorkerResponse& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->RequestId_ = x.RequestId_;
      this->PartNumber_ = x.PartNumber_;
      this->Answers_ = x.Answers_;
    }

    return *this;
  }

  CrackHashWorkerResponse::
  ~CrackHashWorkerResponse ()
  {
  }

  // Answers
  //

  Answers::
  Answers ()
  : ::xml_schema::type (),
    words_ (this)
  {
  }

  Answers::
  Answers (const Answers& x,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    words_ (x.words_, f, this)
  {
  }

  Answers::
  Answers (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f,
           ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    words_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void Answers::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // words
      //
      if (n.name () == "words" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< words_type > r (
          words_traits::create (i, f, this));

        this->words_.push_back (::std::move (r));
        continue;
      }

      break;
    }
  }

  Answers* Answers::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class Answers (*this, f, c);
  }

  Answers& Answers::
  operator= (const Answers& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->words_ = x.words_;
    }

    return *this;
  }

  Answers::
  ~Answers ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace dto
{
  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (const ::std::string& u,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
      ::dto::CrackHashWorkerResponse_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (const ::std::string& u,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
      ::dto::CrackHashWorkerResponse_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (const ::std::string& u,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
      ::dto::CrackHashWorkerResponse_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::std::istream& is,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dto::CrackHashWorkerResponse_ (isrc, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::std::istream& is,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dto::CrackHashWorkerResponse_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::std::istream& is,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::dto::CrackHashWorkerResponse_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::std::istream& is,
                            const ::std::string& sid,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dto::CrackHashWorkerResponse_ (isrc, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::std::istream& is,
                            const ::std::string& sid,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dto::CrackHashWorkerResponse_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::std::istream& is,
                            const ::std::string& sid,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::dto::CrackHashWorkerResponse_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::xercesc::InputSource& i,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
      ::dto::CrackHashWorkerResponse_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::xercesc::InputSource& i,
                            ::xml_schema::error_handler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
      ::dto::CrackHashWorkerResponse_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::xercesc::InputSource& i,
                            ::xercesc::DOMErrorHandler& h,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
      ::dto::CrackHashWorkerResponse_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (const ::xercesc::DOMDocument& doc,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::unique_ptr< ::dto::CrackHashWorkerResponse > (
        ::dto::CrackHashWorkerResponse_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "CrackHashWorkerResponse" &&
        n.namespace_ () == "dto")
    {
      ::std::unique_ptr< ::dto::CrackHashWorkerResponse > r (
        ::xsd::cxx::tree::traits< ::dto::CrackHashWorkerResponse, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "CrackHashWorkerResponse",
      "dto");
  }

  ::std::unique_ptr< ::dto::CrackHashWorkerResponse >
  CrackHashWorkerResponse_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                            ::xml_schema::flags f,
                            const ::xml_schema::properties&)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "CrackHashWorkerResponse" &&
        n.namespace_ () == "dto")
    {
      ::std::unique_ptr< ::dto::CrackHashWorkerResponse > r (
        ::xsd::cxx::tree::traits< ::dto::CrackHashWorkerResponse, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "CrackHashWorkerResponse",
      "dto");
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

